[2022-09-20 23:51:49,058] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: example_bash_operator.also_run_this manual__2022-09-20T23:46:34.020872+00:00 [queued]>
[2022-09-20 23:51:51,173] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: example_bash_operator.also_run_this manual__2022-09-20T23:46:34.020872+00:00 [queued]>
[2022-09-20 23:51:51,178] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-09-20 23:51:51,178] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-09-20 23:51:51,178] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-09-20 23:51:53,506] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): also_run_this> on 2022-09-20 23:46:34.020872+00:00
[2022-09-20 23:51:53,513] {standard_task_runner.py:52} INFO - Started process 7194 to run task
[2022-09-20 23:51:53,650] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'example_bash_operator', 'also_run_this', 'manual__2022-09-20T23:46:34.020872+00:00', '--job-id', '13', '--raw', '--subdir', '/home/***/.local/lib/python3.7/site-packages/***/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmpl5l1id4s', '--error-file', '/tmp/tmpxve2ucdj']
[2022-09-20 23:51:53,651] {standard_task_runner.py:80} INFO - Job 13: Subtask also_run_this
[2022-09-20 23:51:55,045] {task_command.py:369} INFO - Running <TaskInstance: example_bash_operator.also_run_this manual__2022-09-20T23:46:34.020872+00:00 [running]> on host 3bbbf421189d
[2022-09-20 23:51:59,445] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=also_run_this
AIRFLOW_CTX_EXECUTION_DATE=2022-09-20T23:46:34.020872+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-20T23:46:34.020872+00:00
[2022-09-20 23:51:59,513] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-09-20 23:51:59,587] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo "run_id=manual__2022-09-20T23:46:34.020872+00:00 | dag_run=<DagRun example_bash_operator @ 2022-09-20 23:46:34.020872+00:00: manual__2022-09-20T23:46:34.020872+00:00, externally triggered: True>"']
[2022-09-20 23:51:59,740] {subprocess.py:85} INFO - Output:
[2022-09-20 23:51:59,746] {subprocess.py:92} INFO - run_id=manual__2022-09-20T23:46:34.020872+00:00 | dag_run=<DagRun example_bash_operator @ 2022-09-20 23:46:34.020872+00:00: manual__2022-09-20T23:46:34.020872+00:00, externally triggered: True>
[2022-09-20 23:51:59,747] {subprocess.py:96} INFO - Command exited with return code 0
[2022-09-20 23:52:00,785] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=also_run_this, execution_date=20220920T234634, start_date=20220920T235149, end_date=20220920T235200
[2022-09-20 23:52:01,839] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-20 23:52:02,236] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
